"""initial

Revision ID: cba54ef9d496
Revises: 
Create Date: 2026-06-06 18:17:10.236391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cba54ef9d496'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sms_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('whatsapp_sender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('web_form_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('round_robin_pointer', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dealer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dealer_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_dealer_sms_number'), ['sms_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_dealer_web_form_token'), ['web_form_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_dealer_whatsapp_sender'), ['whatsapp_sender'], unique=False)

    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('stock_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trim', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_dealer_id'), ['dealer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_stock_no'), ['stock_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_vin'), ['vin'], unique=False)

    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('SMS', 'WHATSAPP', 'MESSENGER', 'EMAIL', 'WEBFORM', 'PHONE', name='channel'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vehicle_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('NEW', 'AUTO_REPLIED', 'ASSIGNED', 'CLAIMED', 'ENGAGED', 'APPT_SET', 'SHOWED', 'SOLD', 'LOST', 'ESCALATED', 'OPTED_OUT', name='leadstate'), nullable=False),
    sa.Column('assigned_rep', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_dealer_id'), ['dealer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_state'), ['state'], unique=False)

    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_dealer_id'), ['dealer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_lead_id'), ['lead_id'], unique=False)

    op.create_table('consentlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consentlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consentlog_dealer_id'), ['dealer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consentlog_phone'), ['phone'], unique=False)

    op.create_table('leadevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('synced', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leadevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leadevent_dealer_id'), ['dealer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leadevent_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leadevent_synced'), ['synced'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='direction'), nullable=False),
    sa.Column('channel', sa.Enum('SMS', 'WHATSAPP', 'MESSENGER', 'EMAIL', 'WEBFORM', 'PHONE', name='channel'), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_sid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delivery_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_delivery_status'), ['delivery_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_provider_sid'), ['provider_sid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_provider_sid'))
        batch_op.drop_index(batch_op.f('ix_message_lead_id'))
        batch_op.drop_index(batch_op.f('ix_message_delivery_status'))

    op.drop_table('message')
    with op.batch_alter_table('leadevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leadevent_synced'))
        batch_op.drop_index(batch_op.f('ix_leadevent_lead_id'))
        batch_op.drop_index(batch_op.f('ix_leadevent_dealer_id'))

    op.drop_table('leadevent')
    with op.batch_alter_table('consentlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consentlog_phone'))
        batch_op.drop_index(batch_op.f('ix_consentlog_dealer_id'))

    op.drop_table('consentlog')
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_lead_id'))
        batch_op.drop_index(batch_op.f('ix_appointment_dealer_id'))

    op.drop_table('appointment')
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_state'))
        batch_op.drop_index(batch_op.f('ix_lead_phone'))
        batch_op.drop_index(batch_op.f('ix_lead_dealer_id'))

    op.drop_table('lead')
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_vin'))
        batch_op.drop_index(batch_op.f('ix_vehicle_stock_no'))
        batch_op.drop_index(batch_op.f('ix_vehicle_dealer_id'))

    op.drop_table('vehicle')
    with op.batch_alter_table('dealer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dealer_whatsapp_sender'))
        batch_op.drop_index(batch_op.f('ix_dealer_web_form_token'))
        batch_op.drop_index(batch_op.f('ix_dealer_sms_number'))
        batch_op.drop_index(batch_op.f('ix_dealer_slug'))

    op.drop_table('dealer')
    # ### end Alembic commands ###
