"""initial_schema

Revision ID: 82864cde1dc2
Revises: 
Create Date: 2026-06-20 05:13:47.980776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82864cde1dc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sms_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('whatsapp_sender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('web_form_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('round_robin_pointer', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_slug'), 'dealer', ['slug'], unique=True)
    op.create_index(op.f('ix_dealer_sms_number'), 'dealer', ['sms_number'], unique=False)
    op.create_index(op.f('ix_dealer_web_form_token'), 'dealer', ['web_form_token'], unique=True)
    op.create_index(op.f('ix_dealer_whatsapp_sender'), 'dealer', ['whatsapp_sender'], unique=False)
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('stock_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trim', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_dealer_id'), 'vehicle', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_vehicle_stock_no'), 'vehicle', ['stock_no'], unique=False)
    op.create_index(op.f('ix_vehicle_vin'), 'vehicle', ['vin'], unique=False)
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('SMS', 'WHATSAPP', 'MESSENGER', 'EMAIL', 'WEBFORM', 'PHONE', name='channel'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vehicle_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('NEW', 'AUTO_REPLIED', 'ASSIGNED', 'CLAIMED', 'ENGAGED', 'APPT_SET', 'SHOWED', 'SOLD', 'LOST', 'ESCALATED', 'OPTED_OUT', name='leadstate'), nullable=False),
    sa.Column('assigned_rep', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('loss_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_dealer_id'), 'lead', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_lead_phone'), 'lead', ['phone'], unique=False)
    op.create_index(op.f('ix_lead_state'), 'lead', ['state'], unique=False)
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_dealer_id'), 'appointment', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_appointment_lead_id'), 'appointment', ['lead_id'], unique=False)
    op.create_table('consentlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consentlog_dealer_id'), 'consentlog', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_consentlog_phone'), 'consentlog', ['phone'], unique=False)
    op.create_table('leadevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('synced', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leadevent_dealer_id'), 'leadevent', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_leadevent_lead_id'), 'leadevent', ['lead_id'], unique=False)
    op.create_index(op.f('ix_leadevent_synced'), 'leadevent', ['synced'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='direction'), nullable=False),
    sa.Column('channel', sa.Enum('SMS', 'WHATSAPP', 'MESSENGER', 'EMAIL', 'WEBFORM', 'PHONE', name='channel'), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_sid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delivery_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sender_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recipient_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_delivery_status'), 'message', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_message_lead_id'), 'message', ['lead_id'], unique=False)
    op.create_index(op.f('ix_message_provider_sid'), 'message', ['provider_sid'], unique=True)
    op.create_index(op.f('ix_message_recipient_role'), 'message', ['recipient_role'], unique=False)
    op.create_index(op.f('ix_message_sender_role'), 'message', ['sender_role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_sender_role'), table_name='message')
    op.drop_index(op.f('ix_message_recipient_role'), table_name='message')
    op.drop_index(op.f('ix_message_provider_sid'), table_name='message')
    op.drop_index(op.f('ix_message_lead_id'), table_name='message')
    op.drop_index(op.f('ix_message_delivery_status'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_leadevent_synced'), table_name='leadevent')
    op.drop_index(op.f('ix_leadevent_lead_id'), table_name='leadevent')
    op.drop_index(op.f('ix_leadevent_dealer_id'), table_name='leadevent')
    op.drop_table('leadevent')
    op.drop_index(op.f('ix_consentlog_phone'), table_name='consentlog')
    op.drop_index(op.f('ix_consentlog_dealer_id'), table_name='consentlog')
    op.drop_table('consentlog')
    op.drop_index(op.f('ix_appointment_lead_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_dealer_id'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_lead_state'), table_name='lead')
    op.drop_index(op.f('ix_lead_phone'), table_name='lead')
    op.drop_index(op.f('ix_lead_dealer_id'), table_name='lead')
    op.drop_table('lead')
    op.drop_index(op.f('ix_vehicle_vin'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_stock_no'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_dealer_id'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_dealer_whatsapp_sender'), table_name='dealer')
    op.drop_index(op.f('ix_dealer_web_form_token'), table_name='dealer')
    op.drop_index(op.f('ix_dealer_sms_number'), table_name='dealer')
    op.drop_index(op.f('ix_dealer_slug'), table_name='dealer')
    op.drop_table('dealer')
    # ### end Alembic commands ###
